### ISSUE TITLE
Ajout prise en compte nouvelle règle de jeu : plafonnement du nombre de dés maximum utilisable dans un jet.

### ISSUE THREAD

**Issue by JBdAmiens** [stephaned68/WOIN#1]
.

**Comment by stephaned68** [comment]
L'attribut est *Intuition* donc l'abréviation devrait plutôt être **INTU** ?

**Comment by JBdAmiens** [comment]
oui mais faudrait aussi intelligence en attribut

________________________________
De : Stéphane Devouard ***@***.***>
Envoyé : lundi 31 mai 2021 08:54
À : stephaned68/WOIN ***@***.***>
Cc : JBdAmiens ***@***.***>; Author ***@***.***>
Objet : Re: [stephaned68/WOIN] Ajout prise en compte nouvelle règle de jeu : plafonnement du nombre de dés maximum utilisable dans un jet. (#1)


L'attribut est Intuition donc l'abréviation devrait plutôt être INTU ?

**Comment by JBdAmiens** [comment]
le projet à terme dois avoir 3 niveaux, simple (racines de 5 pseudos attributs) moyen (tronc 15 attributs) et avancé (45 compétence)
________________________________
De : Stéphane Devouard ***@***.***>
Envoyé : lundi 31 mai 2021 08:54
À : stephaned68/WOIN ***@***.***>
Cc : JBdAmiens ***@***.***>; Author ***@***.***>
Objet : Re: [stephaned68/WOIN] Ajout prise en compte nouvelle règle de jeu : plafonnement du nombre de dés maximum utilisable dans un jet. (#1)


L'attribut est Intuition donc l'abréviation devrait plutôt être INTU ?

**Comment by stephaned68** [comment]
N'y a-t-il pas LOGique pour l'Intelligence ?
